# Generated by Django 5.0.1 on 2024-01-10 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVisualization', '0004_remove_medicion_sensor_medicion_sensor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medición', 'verbose_name_plural': 'Mediciones'},
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='sensor',
        ),
        migrations.AddField(
            model_name='medicion',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='dataVisualization.sensor'),
        ),
    ]
