# Generated by Django 5.0.1 on 2024-01-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVisualization', '0005_alter_medicion_options_remove_medicion_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataVisualization.sensor'),
        ),
    ]
