# Generated by Django 5.0.1 on 2024-01-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVisualization', '0006_alter_medicion_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='dataVisualization.sensor'),
        ),
    ]
